In [1]:
# imports
import pandas as pd
import  requests

In [41]:
# fetching  the  article  for use
url = "http://mlg.ucd.ie/files/datasets/bbc-fulltext.zip"

response = requests.get(url)
# downloading  the  BBC News articles zip file
with open("bbc.zip", "wb") as f:
    f.write(response.content)

print("download ready")

download ready

In [42]:
#  the  file  is  zipped  so we  need  unzip it  using  this  library
import zipfile

with zipfile.ZipFile("bbc.zip", 'r') as zip_ref:
    zip_ref.extractall(r"C:\Users\adelu\OneDrive\Documents\AI_engineering_intership")

In [43]:
# Now  we call  all  the files  using  (pathlib)
from pathlib import Path

# lets  look at the sub folders 
p = Path(r'C:\Users\adelu\OneDrive\Documents\AI_engineering_intership\bbc')
[x for x in p.iterdir() if x.is_dir()]

# listing all the  individual text  files  in the  folder
list(p.glob('**/*.txt'))

[WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/README.TXT'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/001.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/002.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/003.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/004.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/005.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/006.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/007.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/008.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/009.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/010.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/011.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/012.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/013.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/014.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/015.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/016.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/017.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/018.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/019.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/020.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/021.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/022.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/023.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/024.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/025.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/026.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/027.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/028.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/029.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/030.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/031.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/032.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/033.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/034.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/035.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/036.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/037.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/038.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/039.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/040.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/041.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/042.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/043.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/044.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/045.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/046.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/047.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/048.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/049.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/050.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/051.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/052.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/053.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/054.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/055.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/056.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/057.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/058.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/059.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/060.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/061.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/062.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/063.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/064.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/065.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/066.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/067.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/068.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/069.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/070.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/071.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/072.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/073.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/074.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/075.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/076.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/077.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/078.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/079.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/080.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/081.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/082.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/083.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/084.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/085.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/086.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/087.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/088.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/089.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/090.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/091.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/092.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/093.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/094.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/095.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/096.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/097.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/098.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/099.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/100.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/101.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/102.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/103.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/104.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/105.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/106.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/107.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/108.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/109.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/110.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/111.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/112.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/113.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/114.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/115.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/116.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/117.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/118.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/119.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/120.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/121.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/122.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/123.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/124.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/125.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/126.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/127.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/128.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/129.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/130.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/131.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/132.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/133.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/134.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/135.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/136.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/137.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/138.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/139.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/140.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/141.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/142.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/143.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/144.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/145.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/146.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/147.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/148.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/149.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/150.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/151.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/152.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/153.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/154.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/155.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/156.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/157.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/158.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/159.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/160.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/161.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/162.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/163.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/164.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/165.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/166.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/167.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/168.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/169.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/170.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/171.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/172.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/173.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/174.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/175.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/176.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/177.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/178.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/179.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/180.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/181.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/182.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/183.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/184.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/185.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/186.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/187.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/188.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/189.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/190.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/191.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/192.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/193.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/194.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/195.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/196.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/197.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/198.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/199.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/200.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/201.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/202.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/203.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/204.txt'),
 WindowsPath('C:/Users/adelu/OneDrive/Documents/AI_engineering_intership/bbc/business/205.txt'),

In [44]:
# adding all the text  files  to  a  list 
articles = []

for filepath in p.glob('**/*.txt'):
    if filepath.parent != p:  # update to remove  the readme file from  being  added
        with open(filepath, "r", encoding="utf-8", errors="ignore") as f:
            text = f.read()
            articles.append(text)

In [45]:
# checking  total length for the  list 
print(len(articles))
print(articles[0][:200])

2225
Ad sales boost Time Warner profit

Quarterly profits at US media giant TimeWarner jumped 76% to $1.13bn (£600m) for the three months to December, from $639m year-earlier.

The firm, which is now one o

In [46]:
# converting the  list  into  a Dataframe
df = pd.DataFrame(articles,columns=["Original_text"])
df.head()

                                       Original_text
0  Ad sales boost Time Warner profit\n\nQuarterly...
1  Dollar gains on Greenspan speech\n\nThe dollar...
2  Yukos unit buyer faces loan claim\n\nThe owner...
3  High fuel prices hit BA's profits\n\nBritish A...
4  Pernod takeover talk lifts Domecq\n\nShares in...

In [47]:
# make the all  the  text in the  'Original_text' lowercase for  easy  opeation 
df["lowercase_Original_text"] = df["Original_text"].str.lower()
df

,Original_text,lowercase_Original_text
0,Ad sales boost Time Warner profit\n\nQuarterly...,ad sales boost time warner profit\n\nquarterly...
1,Dollar gains on Greenspan speech\n\nThe dollar...,dollar gains on greenspan speech\n\nthe dollar...
2,Yukos unit buyer faces loan claim\n\nThe owner...,yukos unit buyer faces loan claim\n\nthe owner...
3,High fuel prices hit BA's profits\n\nBritish A...,high fuel prices hit ba's profits\n\nbritish a...
4,Pernod takeover talk lifts Domecq\n\nShares in...,pernod takeover talk lifts domecq\n\nshares in...
...,...,...
2220,BT program to beat dialler scams\n\nBT is intr...,bt program to beat dialler scams\n\nbt is intr...
2221,Spam e-mails tempt net shoppers\n\nComputer us...,spam e-mails tempt net shoppers\n\ncomputer us...
2222,Be careful how you code\n\nA new European dire...,be careful how you code\n\na new european dire...
2223,US cyber security chief resigns\n\nThe man mak...,us cyber security chief resigns\n\nthe man mak...
2224,Losing yourself in online gaming\n\nOnline rol...,losing yourself in online gaming\n\nonline rol...

In [48]:
# removing punctuation from  lowercase_orginal_text
df["No_punctuation"]  =  df["lowercase_Original_text"].str.replace("[^a-zA-Z0-9\s]" ,"" ,regex=True)
df

,Original_text,lowercase_Original_text,No_punctuation
0,Ad sales boost Time Warner profit\n\nQuarterly...,ad sales boost time warner profit\n\nquarterly...,ad sales boost time warner profit\n\nquarterly...
1,Dollar gains on Greenspan speech\n\nThe dollar...,dollar gains on greenspan speech\n\nthe dollar...,dollar gains on greenspan speech\n\nthe dollar...
2,Yukos unit buyer faces loan claim\n\nThe owner...,yukos unit buyer faces loan claim\n\nthe owner...,yukos unit buyer faces loan claim\n\nthe owner...
3,High fuel prices hit BA's profits\n\nBritish A...,high fuel prices hit ba's profits\n\nbritish a...,high fuel prices hit bas profits\n\nbritish ai...
4,Pernod takeover talk lifts Domecq\n\nShares in...,pernod takeover talk lifts domecq\n\nshares in...,pernod takeover talk lifts domecq\n\nshares in...
...,...,...,...
2220,BT program to beat dialler scams\n\nBT is intr...,bt program to beat dialler scams\n\nbt is intr...,bt program to beat dialler scams\n\nbt is intr...
2221,Spam e-mails tempt net shoppers\n\nComputer us...,spam e-mails tempt net shoppers\n\ncomputer us...,spam emails tempt net shoppers\n\ncomputer use...
2222,Be careful how you code\n\nA new European dire...,be careful how you code\n\na new european dire...,be careful how you code\n\na new european dire...
2223,US cyber security chief resigns\n\nThe man mak...,us cyber security chief resigns\n\nthe man mak...,us cyber security chief resigns\n\nthe man mak...
2224,Losing yourself in online gaming\n\nOnline rol...,losing yourself in online gaming\n\nonline rol...,losing yourself in online gaming\n\nonline rol...

In [49]:
# Checks 
df[["Original_text", "No_punctuation"]].head(2)

,Original_text,No_punctuation
0,Ad sales boost Time Warner profit\n\nQuarterly...,ad sales boost time warner profit\n\nquarterly...
1,Dollar gains on Greenspan speech\n\nThe dollar...,dollar gains on greenspan speech\n\nthe dollar...

In [50]:
# Tokenization 
df ["tokens"] = df["No_punctuation"].str.split()
df.head(3)

,Original_text,lowercase_Original_text,No_punctuation,tokens
0,Ad sales boost Time Warner profit\n\nQuarterly...,ad sales boost time warner profit\n\nquarterly...,ad sales boost time warner profit\n\nquarterly...,"[ad, sales, boost, time, warner, profit, quart..."
1,Dollar gains on Greenspan speech\n\nThe dollar...,dollar gains on greenspan speech\n\nthe dollar...,dollar gains on greenspan speech\n\nthe dollar...,"[dollar, gains, on, greenspan, speech, the, do..."
2,Yukos unit buyer faces loan claim\n\nThe owner...,yukos unit buyer faces loan claim\n\nthe owner...,yukos unit buyer faces loan claim\n\nthe owner...,"[yukos, unit, buyer, faces, loan, claim, the, ..."

In [51]:
# import  nltk 
import nltk
nltk.download("stopwords")
from nltk.corpus import stopwords
stop_words = set(stopwords.words("english"))

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\adelu\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [52]:
# removing  stopwords using  (nltk) natural language   toolkit 
df["tokens_clean"] = df["tokens"].apply(lambda token_list: [word for word in token_list if word not in stop_words])
df.head(2)

,Original_text,lowercase_Original_text,No_punctuation,tokens,tokens_clean
0,Ad sales boost Time Warner profit\n\nQuarterly...,ad sales boost time warner profit\n\nquarterly...,ad sales boost time warner profit\n\nquarterly...,"[ad, sales, boost, time, warner, profit, quart...","[ad, sales, boost, time, warner, profit, quart..."
1,Dollar gains on Greenspan speech\n\nThe dollar...,dollar gains on greenspan speech\n\nthe dollar...,dollar gains on greenspan speech\n\nthe dollar...,"[dollar, gains, on, greenspan, speech, the, do...","[dollar, gains, greenspan, speech, dollar, hit..."

In [53]:
# Save  to CSv  we  convert  to  from token list  back  to  a  string 
df["cleaned_df"] = df["tokens_clean"].apply(lambda tokens_list: " ".join(tokens_list))
df

,Original_text,lowercase_Original_text,No_punctuation,tokens,tokens_clean,cleaned_df
0,Ad sales boost Time Warner profit\n\nQuarterly...,ad sales boost time warner profit\n\nquarterly...,ad sales boost time warner profit\n\nquarterly...,"[ad, sales, boost, time, warner, profit, quart...","[ad, sales, boost, time, warner, profit, quart...",ad sales boost time warner profit quarterly pr...
1,Dollar gains on Greenspan speech\n\nThe dollar...,dollar gains on greenspan speech\n\nthe dollar...,dollar gains on greenspan speech\n\nthe dollar...,"[dollar, gains, on, greenspan, speech, the, do...","[dollar, gains, greenspan, speech, dollar, hit...",dollar gains greenspan speech dollar hit highe...
2,Yukos unit buyer faces loan claim\n\nThe owner...,yukos unit buyer faces loan claim\n\nthe owner...,yukos unit buyer faces loan claim\n\nthe owner...,"[yukos, unit, buyer, faces, loan, claim, the, ...","[yukos, unit, buyer, faces, loan, claim, owner...",yukos unit buyer faces loan claim owners embat...
3,High fuel prices hit BA's profits\n\nBritish A...,high fuel prices hit ba's profits\n\nbritish a...,high fuel prices hit bas profits\n\nbritish ai...,"[high, fuel, prices, hit, bas, profits, britis...","[high, fuel, prices, hit, bas, profits, britis...",high fuel prices hit bas profits british airwa...
4,Pernod takeover talk lifts Domecq\n\nShares in...,pernod takeover talk lifts domecq\n\nshares in...,pernod takeover talk lifts domecq\n\nshares in...,"[pernod, takeover, talk, lifts, domecq, shares...","[pernod, takeover, talk, lifts, domecq, shares...",pernod takeover talk lifts domecq shares uk dr...
...,...,...,...,...,...,...
2220,BT program to beat dialler scams\n\nBT is intr...,bt program to beat dialler scams\n\nbt is intr...,bt program to beat dialler scams\n\nbt is intr...,"[bt, program, to, beat, dialler, scams, bt, is...","[bt, program, beat, dialler, scams, bt, introd...",bt program beat dialler scams bt introducing t...
2221,Spam e-mails tempt net shoppers\n\nComputer us...,spam e-mails tempt net shoppers\n\ncomputer us...,spam emails tempt net shoppers\n\ncomputer use...,"[spam, emails, tempt, net, shoppers, computer,...","[spam, emails, tempt, net, shoppers, computer,...",spam emails tempt net shoppers computer users ...
2222,Be careful how you code\n\nA new European dire...,be careful how you code\n\na new european dire...,be careful how you code\n\na new european dire...,"[be, careful, how, you, code, a, new, european...","[careful, code, new, european, directive, coul...",careful code new european directive could put ...
2223,US cyber security chief resigns\n\nThe man mak...,us cyber security chief resigns\n\nthe man mak...,us cyber security chief resigns\n\nthe man mak...,"[us, cyber, security, chief, resigns, the, man...","[us, cyber, security, chief, resigns, man, mak...",us cyber security chief resigns man making sur...
2224,Losing yourself in online gaming\n\nOnline rol...,losing yourself in online gaming\n\nonline rol...,losing yourself in online gaming\n\nonline rol...,"[losing, yourself, in, online, gaming, online,...","[losing, online, gaming, online, role, playing...",losing online gaming online role playing games...

In [54]:
# save to csv
df[["Original_text", "cleaned_df"]].to_csv("bbc_cleaned.csv", index=False)